### ISSUE TITLE
emo package during install

### ISSUE THREAD

**Issue by bhive01** [abresler/realtR#3] opened 2018-05-14 21:03 UTC
Going through the tutorial here:
http://asbcllc.com/r_packages/realtR/2018/introduction/

emo isn't installed through the normal installation process. I believe this is because it's github-only. Everything else seems to install (or I already had it) fine.

# install.packages("devtools")
devtools::install_github("hadley/emo")

**Comment by abresler** [comment] 2018-05-14 21:13
Duplicate of prior issue but will add this to the readme

**Closed by abresler** 2018-05-14 21:13 UTC
